name: Run MATLAB
on:
  workflow_dispatch: {}
  push: {}
jobs:
  my-job:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2025aU1
          cache: true
      - name: Run MATLAB command
        uses: matlab-actions/run-command@v2
        with:
          command: plot(1)
            
