name: Run MATLAB
on:
  workflow_dispatch: {}
  push: {}
jobs:
  my-job:
    runs-on: macos-14
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Download and mount MATLAB DMG
        run: |
          wget https://esd.mathworks.com/R2024a/R2024a_Update_4/archives/R2024a_Update_4_macOSIntelProcessor.dmg
          hdiutil attach R2024a_Update_4_macOSIntelProcessor.dmg
      - name: Install MATLAB
        run: |
          wget https://www.mathworks.com/mpm/maci64/mpm
          chmod +x mpm
          ./mpm install --release=R2024a --source=/path/to/mounted/image --products MATLAB Simulink
      - name: Run command
        uses: matlab-actions/run-command@v2
        with:
          command: disp('hello world')
